import type { Metadata } from 'next';
import '../globals.css';
import { i18nConfig } from '@/i18nConfig';
import { dir } from 'i18next';

export const metadata: Metadata = {
  title: 'BB fanchants',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className="bg-gray6-black bg-custom-gradient overflow-hidden">
        {children}
      </body>
    </html>
  );
}
